var employeesList = [
    {
      id: 1,
      name: "John Wick",
      jobTitle: "Project Manager",
      department: "Managers",
      location: "Hyderabad",
      age: 28,
      salary: "1450000",
      actions: "Action",
    },
    {
      id: 2,
      name: "Manish",
      jobTitle: "React Developer",
      department: "Developers",
      location: "Chennai",
      age: 28,
      salary: "115000",
      actions: "Action",
    },
    {
      id: 3,
      name: "Akhil",
      jobTitle: "Design Manager",
      department: "Designers",
      location: "Banglore",
      age: 25,
      salary: "1250000",
      actions: "Action",
    },
    {
      id: 4,
      name: "Mary",
      jobTitle: "Test Engineer",
      department: "Testers",
      location: "Pune",
      age: 21,
      salary: "1450000",
      actions: "Action",
    },
    {
      id: 5,
      name: "Srujan",
      jobTitle: "Project Manager",
      department: "Managers",
      location: "Hyderabad",
      age: 28,
      salary: "1450000",
      actions: "Action",
    },
    {
      id: 6,
      name: "Michael",
      jobTitle: "Testing Lead",
      department: "Tester",
      location: "Chennai",
      age: 28,
      salary: "1450000",
      actions: "Action",
    },
    {
      id: 7,
      name: "Nikhil",
      jobTitle: "Tech Manager",
      department: "Manager",
      location: "Bangalore",
      age: 26,
      salary: "1230020",
      actions: "Action",
    },
    {
      id: 8,
      name: "Priya",
      jobTitle: "Developer",
      department: "Developers",
      location: "Chennai",
      age: 22,
      salary: "1413020",
      actions: "Action",
    },
    {
      id: 9,
      name: "Nicholas",
      jobTitle: "Tester",
      department: "Tester",
      location: "Pune",
      age: 29,
      salary: "1123112",
      actions: "Action",
    },
    {
      id: 10,
      name: "Master",
      jobTitle: "Designer",
      department: "Designers",
      location: "Hyderabad",
      age: 31,
      salary: "910000",
      actions: "Action",
    },
  
    {
      id: 11,
      name: "Srinivas",
      jobTitle: "Testing",
      department: "Managers",
      location: "Chennai",
      age: 28,
      salary: "1250000",
      actions: "Action",
    },
    {
      id: 12,
      name: "Vishnu",
      jobTitle: "React Developer",
      department: "Developers",
      location: "Hyderabad",
      age: 28,
      salary: "115000",
      actions: "Action",
    },
    {
      id: 13,
      name: "Harry",
      jobTitle: "Design Manager",
      department: "Designers",
      location: "Banglore",
      age: 25,
      salary: "120000",
      actions: "Action",
    },
    {
      id: 14,
      name: "Kranthi",
      jobTitle: "Mern Developer",
      department: "Developers",
      location: "Pune",
      age: 20,
      salary: "1050000",
      actions: "Action",
    },
    {
      id: 15,
      name: "Smrithi",
      jobTitle: "Project Manager",
      department: "Managers",
      location: "Bangalore",
      age: 34,
      salary: "450000",
      actions: "Action",
    },
    {
      id: 16,
      name: "Mike",
      jobTitle: "Designer Lead",
      department: "Designers",
      location: "Chennai",
      age: 35,
      salary: "1100000",
      actions: "Action",
    },
  
    {
      id: 17,
      name: "Jock",
      jobTitle: "Manager",
      department: "Managers",
      location: "Hyderabad",
      age: 22,
      salary: "1400000",
      actions: "Action",
    },
    {
      id: 18,
      name: "Ranvir",
      jobTitle: "Testing Lead",
      department: "Tester",
      location: "Pune",
      age: 28,
      salary: "1050000",
      actions: "Action",
    },
    {
      id: 19,
      name: "Nikhil",
      jobTitle: "Tech Manager",
      department: "Manager",
      location: "Bangalore",
      age: 26,
      salary: "1230020",
      actions: "Action",
    },
    {
      id: 20,
      name: "Sreeja",
      jobTitle: "Developer",
      department: "Developers",
      location: "Chennai",
      age: 21,
      salary: "1413020",
      actions: "Action",
    },
    {
      id: 21,
      name: "Nikki",
      jobTitle: "Tester",
      department: "Tester",
      location: "Pune",
      age: 21,
      salary: "923112",
      actions: "Action",
    },
    {
      id: 22,
      name: "Vijay",
      jobTitle: "Designer",
      department: "Designers",
      location: "Hyderabad",
      age: 31,
      salary: "910000",
      actions: "Action",
    },
  ];
  
  module.exports.employeesList = employeesList;
  